import m from "mithril"

var Lorem = {
    view() {
        return [
            m(".jumbotron.jumbotron-fluid.text-center",
                m(".container.fancy",
                    m("h1.display-4", "Lorem ipsum - long page"),
                    m("p.lead.text-muted", "As you can see- when you scroll the page the header obtain shadow")
                )
            ),
            m(".container.fancy",
                m("p.lead", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse faucibus ornare justo, at rhoncus lorem suscipit at. Integer lobortis sapien in lectus lobortis placerat. Aenean sit amet purus accumsan, consequat mi nec, lobortis velit. Etiam accumsan venenatis risus, a elementum lectus efficitur ac. Fusce convallis, nisi at commodo hendrerit, dolor nisi dapibus lorem, sed tristique urna nibh eget eros. Integer ut cursus ante. Nullam tristique, nisi vitae vestibulum lobortis, nisi turpis pretium purus, a laoreet nisl urna iaculis orci. Donec congue ullamcorper lacus, ut maximus nisi dapibus eu. Cras scelerisque pellentesque diam, at posuere massa gravida non."),
                m("p", "Praesent at dignissim mauris, tincidunt cursus ipsum. Vestibulum pharetra nulla vel tortor pulvinar, at suscipit tellus malesuada. Morbi vestibulum in nulla et lacinia. Integer condimentum lobortis nisl sed tincidunt. Etiam id tortor lobortis, lobortis dui sed, scelerisque nunc. Etiam porta ipsum sit amet magna pharetra faucibus in ut enim. Nullam eu neque posuere, sagittis massa eu, varius lectus. Integer condimentum felis in massa porta, eget venenatis quam mollis. Nullam ut vehicula nunc. Nunc fringilla consectetur diam et hendrerit. Pellentesque in ipsum laoreet, fermentum lectus eu, venenatis leo. Maecenas volutpat eget quam molestie accumsan. Praesent condimentum, neque non porta bibendum, turpis purus eleifend mauris, eget ornare nisi nisl eget leo."),
                m("p", "In varius iaculis mauris, vitae posuere magna congue eu. Morbi vitae bibendum nisi. Integer at vulputate lorem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis in felis est. Integer aliquam eros ac est congue ultricies. Sed vehicula condimentum tempus. Ut sed blandit risus. Nam a augue lacinia, laoreet risus sed, pretium enim. Nam vitae maximus ipsum, aliquet sagittis diam. Quisque tincidunt metus quis diam tristique, vel dapibus arcu congue. Sed efficitur ultrices scelerisque. Nunc porta posuere mauris. Pellentesque eu leo non nulla convallis viverra non quis libero. Nulla consequat tempus interdum. Mauris eget lectus rutrum, congue nunc vitae, dictum neque."),
                m("p", "Curabitur quis massa neque. Duis suscipit ut urna vel maximus. Proin auctor ipsum nec lacus condimentum sagittis. Morbi congue et risus venenatis faucibus. Curabitur ornare, metus et vehicula porta, velit nibh interdum erat, vel mattis nulla elit at erat. Nullam quis purus viverra, consequat odio in, vestibulum sapien. Aenean dignissim non nisl at sollicitudin. Maecenas vel gravida purus, vel sodales lorem. Donec dignissim sit amet enim nec cursus."),
                m("p", "Praesent suscipit luctus sem. Duis placerat, ante eget lacinia posuere, est orci pulvinar sapien, ut rutrum elit justo id urna. In commodo sem sit amet aliquet blandit. Nam id cursus elit. Proin mauris nulla, tincidunt sed ornare id, eleifend a dolor. Nullam hendrerit vel augue eget placerat. Cras sed lorem semper risus ullamcorper feugiat. Donec posuere pretium ante, a pellentesque tellus efficitur ac. Maecenas laoreet rutrum arcu, imperdiet efficitur dolor egestas vitae. Curabitur quis mollis lorem, quis tincidunt nunc. Phasellus maximus, nunc at vulputate rutrum, libero velit laoreet leo, vitae scelerisque est lectus ac urna. Quisque blandit non dui non auctor. Aliquam suscipit sem augue, a commodo augue eleifend eu. Cras mollis vehicula consequat."),
                m("p", "Duis enim risus, facilisis et ipsum a, lacinia sagittis neque. Vivamus laoreet vestibulum porttitor. Nulla malesuada arcu sapien, accumsan suscipit libero malesuada nec. Quisque sagittis at nulla eget auctor. Suspendisse libero mi, elementum nec enim eu, egestas consequat ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper, leo ac dictum egestas, lectus felis tempus nisi, ac pellentesque ante quam ac libero. Proin mattis erat quis augue faucibus sollicitudin. Nullam enim erat, luctus vel dolor nec, sollicitudin euismod sem. Cras ut diam ex. Aenean vitae malesuada mauris. Duis quis libero in justo rutrum rhoncus eget eu dui. Sed quis urna dapibus, molestie nisl vitae, feugiat libero. Suspendisse vitae est in turpis iaculis feugiat egestas sit amet ante. Suspendisse at odio ante. Fusce ipsum lacus, accumsan quis luctus vitae, sodales ut mauris."),
                m("p", "Aliquam erat volutpat. Praesent fermentum, ligula vulputate scelerisque cursus, enim arcu condimentum ex, eu fermentum ante nulla eget metus. Maecenas porttitor mi vitae consectetur mollis. Fusce pretium eros non euismod pretium. Maecenas elementum varius massa. Donec cursus sapien tempus sem porta maximus. Phasellus lacinia tempus interdum. Integer risus tellus, convallis suscipit gravida id, fermentum nec magna. Aliquam et accumsan felis. Aenean vel volutpat dui, eu ultricies turpis."),
                m("p", "Nam tincidunt eleifend odio, id vulputate diam dictum ut. Praesent sit amet dolor tincidunt, dignissim dui ac, pretium orci. Quisque mattis eros in magna hendrerit euismod. Duis vestibulum, mi molestie scelerisque pulvinar, ipsum tortor varius purus, id porttitor nisl enim in massa. Donec nunc magna, auctor id ante et, dapibus congue nunc. Praesent vestibulum urna in lectus tincidunt, id imperdiet dui sagittis. Cras vehicula diam eu fringilla faucibus. Suspendisse luctus tincidunt erat vel placerat. Donec purus est, volutpat quis viverra nec, dapibus vitae erat. Vivamus iaculis sit amet leo consectetur mollis."),
                m("p", "Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris non magna dignissim, auctor neque sed, vehicula risus. Duis viverra scelerisque sem non efficitur. Nam pretium velit eu maximus aliquet. Nullam cursus orci nunc, eu pellentesque nisl suscipit a. Morbi semper mollis massa non pulvinar. Pellentesque eu eros id ante lobortis pulvinar a sit amet turpis. Donec ultrices tristique orci ut tempus."),
                m("p", "Nullam eget elit id magna convallis commodo eu a mi. Aenean felis leo, hendrerit vel venenatis non, viverra et justo. Nulla facilisi. Vestibulum nec felis in libero convallis bibendum ut eu lorem. In pulvinar libero massa, sit amet pulvinar nisl consequat ut. Morbi porttitor turpis nec egestas faucibus. Phasellus aliquam pulvinar nibh, interdum auctor lectus malesuada nec. Cras eu sagittis mauris. Quisque eu elit ut risus tincidunt commodo vel sit amet quam.")
            )
        ]
    }
}

export default Lorem
